<?php
$lang["TITLE1"] = "Stay in touch";
$lang["TITLE2"] = "Last news";
$lang["TITLE_NAME"] = "TITLE_NAME_EN";
$lang["TITLE_DESCRIPTION"] = "TITLE_DESCRIPTION_EN";
$lang["NAME_NEWS"] = "PROPERTY_NAME_EN_VALUE";
$lang["CATEGORY"] = "PROPERTY_CATEGORY_EN_VALUE";
$lang["PROJECTS_TITLE"] = "Projects";
$lang["NAME_PROJECT"] = "PROPERTY_NAME_EN_VALUE";
$lang["PROJECTS_DESCRIPTION_SMALL"] = "PROPERTY_SMALL_TEXT_CARD_EN_VALUE";
$lang["NEWS_COMPANY_TITLE"] = "Company news";
$lang["FULL_NEWS_NAME"] = "PROPERTY_FULL_NEWS_EN_VALUE";
$lang["NEWS_DESCRIPTION_DETAIL"] = "DETAIL_TEXT";
$lang["NEWS_DESCRIPTION_SMALL"] = "PROPERTY_SMALL_TEXT_CARD_EN_VALUE";
